### ISSUE TITLE
What's going on with this project?

### ISSUE THREAD

**Issue by xaviergmail** [07kit/07kit#30]
Hi, just wanted to know the current state of this project.

api.07kit.com 302 redirects to a gambling site, and registration seems to be broken on the website as well.

This looks like a very nice client and I'd like to pitch in. Keep me informed!

**Comment by aiecee** [comment]
We decided to stop development as we, the devs, lost interest as no one was using in so there was no motivation to carry it on. Left it up as a learning resource for those who want it.

**Comment by xaviergmail** [comment]
That's a bummer :(
I am confident that, with enough exposure, this could blow out every other
third party client out there.

Would it be possible to release some documentation / tools for generating
the mappings (hooks.json)?

**Comment by Eleng555** [comment]
I'd also be interested in more info on hooks.json

**Comment by aiecee** [comment]
Tools no, this is because using the hooks.json generated people would be able to make bots for the game. One place to take a look for this sort of thing is rs-hacking.com pretty basic stuff on what's needed.

**Comment by rvbiljouw** [comment]
@Eleng555 @xaviergmail https://github.com/07kit/07kit/commit/30d3d82ed7a19dac9356dc33e67ee943c33fc1dd
