### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by ghost** [07kit/07kit#31]
How would i access the client itself or remove the registration/logging in process?

**Comment by aiecee** [comment]
Best way is to create a fake user in the code and the client should load. However, without the hooks it won't work

**Comment by ghost** [comment]
Are the hooks.json updated, if not is it possible for you to run the updater?

**Comment by aiecee** [comment]
They're a re not an no it isn't possible as I don't have the updater

**Comment by ghost** [comment]
How would i be able to update them? Really wanna start working on the project.

**Comment by aiecee** [comment]
Take a look at issue #30

**Comment by rvbiljouw** [comment]
@flosd
